### ISSUE TITLE
The array field returns the wrong value for "path" in version 1.5.18 to 1.5.22

### ISSUE THREAD

**Issue by mlarman70** [gitana/alpaca#427] opened 2016-10-07 16:21 UTC
On an array field the path does not include the path of it's parent.

In 1.5.17 if the path was "/myarray[0]/property" then the same definition in 1.5.18 to 1.5.22 has the path of "/[0]/property" 

This means the path returned cannot be used to later find the field by path.

**Comment by christoph007** [comment] 2017-03-16 12:25
I seems to me that the problem is in ArrayField.js.

I've replaced this code:

```
                    var idx = v.path.lastIndexOf('/');
                    var lastSegment = v.path.substring(idx+1);
                    if (lastSegment.indexOf("[") < 0 && lastSegment.indexOf("]") < 0)
                    {
                        lastSegment = lastSegment.substring(lastSegment.indexOf("[") + 1, lastSegment.indexOf("]"));
                    }

                    if (lastSegment !== i)
                    {
                        v.prePath = v.path;
                        v.path = v.path.substring(0, idx) + "/[" + i + "]";
                    }
```

by

```
                    var idx = v.path.lastIndexOf('/');
                    var lastSegment = v.path.substring(idx+1);
                    if (lastSegment.indexOf("[") > 0 && lastSegment.indexOf("]") > 0)
                    {
                        arrayIndex = lastSegment.substring(lastSegment.indexOf("[") + 1, lastSegment.indexOf("]"));
                    }

                    if (arrayIndex !== i)
                    {
                        v.prePath = v.path;
                        //v.path = v.path.substring(0, idx) + "/[" + i + "]"
                        var prefix= v.path.substring(0, v.path.lastIndexOf('['));
                        v.path = prefix + "[" + i + "]";
                    }
```
Note that I replaced <0 by >0 in line 3. I think <0 doesn't make sense at all.

Strangely enough, this code is much older than version 1.5.17. Maybe the structure of the paths has changed at some point?

**Comment by mlarman70** [comment] 2017-04-11 09:02
I think when I first noticed this I thought 1.5.17 was working,  I have subsequently found that this does also happen in 1.5.17 too.

**Comment by uzquiano** [comment] 2017-05-31 19:11
This has been resolved in head.  Thanks!

**Closed by uzquiano** 2017-05-31 19:11 UTC

**Comment by mlarman70** [comment] 2017-06-02 07:52
Thats great news looking forward to the next release.
