### ISSUE TITLE
Problem with Objects

### ISSUE THREAD

**Issue by billbarsch** [gitana/alpaca#281] opened 2015-07-27 17:26 UTC
@uzquiano  @arthurportas 
Now my Object data is like that:
The input names disappeared :-( and are just nunbers
Is it just with me? Can anybody check if its true?

```javascript
{
    "_0": "ativo",
    "_1": "",
    "_10": "",
    "_11": "",
    "_12": " ",
    "_13": "",
    "_14": "",
    "_15": "",
    "_16": "",
    "_17": "",
    "_2": "lalala",
    "_3": "",
    "_4": "",
    "_5": "",
    "_6": "",
    "_7": "",
    "_8": "",
    "_9": ""
}
```

**Comment by uzquiano** [comment] 2015-07-27 17:27
Can you post some code to reproduce (or send to support@cloudcms.com)?  It's certainly possible since you're using head.  Let's get it fixed!

**Comment by uzquiano** [comment] 2015-07-31 17:57
I believe a fix for this was checked into master.

**Comment by billbarsch** [comment] 2015-07-31 18:18
Hello Michael! I try to compile alpaca some days ago with no success, so I can´t reproduce tihs issue using the last alpaca GitHub code. My alpaca.js file was updated by me line by line applying your changes and than this error occurs. I know it is an error becouse your changes fix the array problem but than a new problem shows up on objects.
I´ll have to wait the alpaca 1.5.12 be released to check your real changes. I´m trying to complie it on Windows and Linux but node, bower, gump... and all those thinks are new to me.

**Comment by uzquiano** [comment] 2015-08-01 04:32
1.5.12 is out.  Give that a shot and if it doesn't work, feel free to re-open.

**Closed by uzquiano** 2015-08-01 04:32 UTC
