### ISSUE TITLE
removeItem doesn't work,

### ISSUE THREAD

**Issue by meisam3322** [gitana/alpaca#301] opened 2015-09-01 08:04 UTC
hi. nice work. i like it and i really need it. but removeItem function or removeField not work. i checked on website samples and had the same problem. 
unfortunatelly no body's asked about removeItem in issue. i tried to solved and i got this line in alpaca.js return undefined :: i traced code follow and got this part that goes on by defined for childField variable , so alpaca remove nothing...

        removeItem: function(propertyId, callback)
        {
            var self = this;
            var childField = this.childrenByPropertyId[propertyId];
.....
.....
.....

childField  variable  return undefined unfortunatelly . i am waiting for your help.
thank you so much

**Comment by meisam3322** [comment] 2015-09-01 08:20
I solved it by one of my best friend ::

in 

    removeItem: function(propertyId, callback)
    {
        var self = this;
        var childField = this.childrenByPropertyId[propertyId];
.....
.....
.....

try to add this line before var childField ::

var propertyId = (this.childrenById[propertyId].propertyId);

so we have ::

        removeItem: function(propertyId, callback)
        {
            var self = this;
            var propertyId = (this.childrenById[propertyId].propertyId);     
            var childField = this.childrenByPropertyId[propertyId];

.....
.....
.....

**Comment by m4ttls** [comment] 2015-09-01 16:45
Hi there, I fix it by adding these lines in form-builder.js
```javascript
var indextoremove = top.children.indexOf(field);
if (indextoremove != -1){
  top.children.splice(indextoremove,1);
}
```
So 
```javascript
    var removeField = function(alpacaId)
    {
        var field = Alpaca.fieldInstances[alpacaId];

        var parentField = field.parent;
        parentField.removeItem(alpacaId, function() {
            var top = findTop(field);
            var indextoremove = top.children.indexOf(field);
            if (indextoremove != -1){
            	top.children.splice(indextoremove,1);
            }
            regenerate(top);
        });
    };
```

**Comment by MarkFreedman** [comment] 2015-10-30 18:20
@meisam3322 I'm wondering why you didn't commit this change. Is it really a bug, or is it that the Form Builder sample app is calling it incorrectly? Should the change have been in the calling code instead (the removeField function of form-builder.js)?

**Comment by cniesen** [comment] 2015-10-30 18:26
There's a pull request to fix this and a couple other problems with the form builder: https://github.com/gitana/alpaca/pull/316

**Comment by MarkFreedman** [comment] 2015-10-30 18:32
Thanks, @cniesen. That does confirm that the issue is form builder-specific :)

**Comment by jango** [comment] 2015-11-19 02:30
Hi Mark, any idea when this will be merged & is the a plan to update the website with the new version of the form builder or am I better of building it locally?

**Comment by MarkFreedman** [comment] 2015-11-19 02:46
That's a good question, @jango. I'm not a contributor (yet), so I don't actually know what the plans are. I'm really surprised these were not merged in yet (to both the core and Form Builder). But I made some of the changes to my local copy as well, and those problems were resolved. As a matter of fact, I'm tearing apart Form Builder and building a version for my client. I'm considering generalizing it and contributing a more fleshed-out version here in a few months.

**Comment by uzquiano** [comment] 2016-03-05 14:55
I think these have been fixed in head.  @cniesen contributed a few fixes and some PRs were merged.  I'm going to close this ticket.  If anyone runs into this again, feel free to submit another ticket.

Also, bear in mind that the "form builder" is just an example that was put together one afternoon while drinking coffee at a Starbucks in Cleveland, Ohio.  It turns out to have become pretty popular but it isn't a formal part of the Alpaca project.  I'm sure it'll have bugs.  If anyone out there wants to submit fixes (as @cniesen and others have done), we'll include them as it benefits others in the community.  Some great initiative from @MarkFreedman and others too.  Would love to see that stuff as part of Alpaca or otherwise open source for the community.

**Closed by uzquiano** 2016-03-05 14:55 UTC
