### ISSUE TITLE
Validation in 1.5.4 works, but not in 1.5.7

### ISSUE THREAD

**Issue by PiQ99** [gitana/alpaca#217] opened 2015-02-20 14:27 UTC
Hey guys,
I had to notice, that validation since 1.5.5 is broken. If I use the following minimal schema I am able to submit the form. It does not matter, if required fields are entered or not. In contrast to this, the same schema in 1.5.4 is not allowed to be submitted.

http://jsfiddle.net/PiQ99/zt25ctx4/ (just change the version of alpaca to 1.5.5+)
--> `<script type="text/javascript" src="http://code.cloudcms.com/alpaca/1.5.7/bootstrap/alpaca.min.js"></script>`

Thanks for investigating this problem :)

**Comment by arthurportas** [comment] 2015-03-07 21:09
Hi,
thanks for reporting this.
Your fiddle is not rendering very well, so i reproduced it in codepen http://codepen.io/arthurportas/pen/jEvwqL .
As mentioned since 1.5.4 until latest it's broken.

Cheers,

**Comment by uzquiano** [comment] 2015-03-08 01:38
I believe this is fixed in master.

The objects documentation example #10 reproduces a similar scenario.  The issue may have been that the Alpaca.fieldApplyFieldAndChildren method had a bug in it where it didn't crawl down deeply nested structures to reset the hideInitValidationError flag on deeper nested fields.  In the example from codepen.io, the schema was double nested (like example #10).

@piQ99 - would you be able to grab a build from master and try it out?

**Comment by arthurportas** [comment] 2015-03-08 21:04
Hi,

@uzquiano  @piQ99 latest build corrects this issue. Updated example at [codepen.io,](http://codepen.io/arthurportas/pen/jEvwqL) using latest build from master.
Great job, this project rocks!

**Closed** 2015-03-13 11:10 UTC
